---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: python-ruff-format
        name: python ruff format
        entry: ruff format
        language: system
        files: \.(py|pyi)$
