---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: python-ruff-format
        name: python ruff format
        entry: uvx ruff format
        language: system
        files: \.(py|pyi)$

      - id: python-ruff-check
        name: python ruff check
        entry: uvx ruff check
        language: system
        files: \.(py|pyi)$

      - id: ty-check
        name: ty check (ingestion)
        entry: uv run --project ingestion ty check
        language: system
        pass_filenames: false
        require_serial: true
        files: ^ingestion/.*\.py$

      - id: sqlfluff-fix
        name: sqlfluff fix (jinja)
        entry: bash -c 'cd transformation && uv run sqlfluff fix --ignore-local-config --config .sqlfluff'
        language: system
        pass_filenames: false
        files: ^transformation/.*\.sql$
        exclude: ^transformation/(target|dbt_packages|macros|\.venv)/

      - id: sqlfluff-lint
        name: sqlfluff lint (jinja)
        entry: bash -c 'cd transformation && uv run sqlfluff lint --ignore-local-config --config .sqlfluff'
        language: system
        pass_filenames: false
        files: ^transformation/.*\.sql$
        exclude: ^transformation/(target|dbt_packages|macros|\.venv)/
