# =============================================================================
# Group Variables - PostgreSQL Server
# =============================================================================

---
postgresql_allowed_cidrs:
  - "10.218.20.0/24"
