# =============================================================================
# Ansible Inventory — Dynamic Host and Group Resources
# =============================================================================
# Uses the ansible/ansible Terraform provider to create ansible_host and
# ansible_group resources. Also writes a local INI inventory file for direct
# ansible-playbook usage.
# =============================================================================

# -----------------------------------------------------------------------------
# Ansible Host Resources — one per k3s node
# -----------------------------------------------------------------------------
resource "ansible_host" "k3s_nodes" {
  for_each = var.k3s_nodes

  name   = each.key
  groups = ["k3s_servers"]

  variables = {
    ansible_host = split("/", each.value.ip_addr)[0]  # Remove CIDR suffix
    ansible_user = var.ansible_user
  }
}

# -----------------------------------------------------------------------------
# Ansible Group Resource — k3s_servers
# -----------------------------------------------------------------------------
resource "ansible_group" "k3s_servers" {
  name = "k3s_servers"

  variables = {
    ansible_ssh_private_key_file = local.ssh_key_path_ansible
  }
}

# -----------------------------------------------------------------------------
# Local Inventory File — INI format for ansible-playbook
# -----------------------------------------------------------------------------
# Writes the inventory to a local file so ansible-playbook can be run
# independently of Terraform. File is re-created whenever hosts change.
# -----------------------------------------------------------------------------
resource "local_file" "ansible_inventory" {
  content = <<-EOF
    # =============================================================================
    # Ansible Inventory — k3s Cluster
    # =============================================================================
    # Generated by Terraform. Do not edit manually.
    # Run `terraform apply` to regenerate if VM IPs change.
    # =============================================================================

    [k3s_servers]
    %{for name, config in var.k3s_nodes~}
    ${name} ansible_host=${split("/", config.ip_addr)[0]} ansible_user=${var.ansible_user}
    %{endfor~}

    [k3s_servers:vars]
    ansible_ssh_private_key_file=${local.ssh_key_path_ansible}
    ansible_python_interpreter=/usr/bin/python3

    # =============================================================================
    # Host Groups for Convenience
    # =============================================================================

    [k3s_first_node]
    ${keys(var.k3s_nodes)[0]}

    [k3s_other_nodes]
    %{for i in range(1, length(keys(var.k3s_nodes)))~}
    ${keys(var.k3s_nodes)[i]}
    %{endfor~}
  EOF

  filename        = "${path.module}/../../ansible/inventory/hosts.ini"
  file_permission = "0644"
}
