airflowVersion: "3.2.0"
defaultAirflowTag: "3.2.0"
executor: KubernetesExecutor

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/RichardNooooh/EveOnlineAnalytics.git
    branch: master
    subPath: "orchestration/dags"
    period: 60s
    recommendedProbeSetting: true
#   credentialsSecret: airflow-app-secrets # only needed if repo requires auth

data:
  metadataSecretName: airflow-app-secrets

config:
  api:
    base_url: "https://eve-airflow.lab.answerisnoh.dev"

apiServer:
  args: ["bash", "-c", "exec airflow api-server --proxy-headers"]
  env:
    - name: FORWARDED_ALLOW_IPS
      value: "*"
  service:
    type: ClusterIP

ingress:
  apiServer:
    enabled: true
    ingressClassName: traefik
    path: /
    pathType: ImplementationSpecific
    hosts:
      - name: eve-airflow.lab.answerisnoh.dev

postgresql:
  enabled: false # Airflow metadata uses the external PostgreSQL Proxmox VM from ADR-018, not an in-cluster chart

redis:
  enabled: false # Kubernetes Executor does not need redis

fernetKeySecretName: airflow-app-secrets
apiSecretKeySecretName: airflow-app-secrets

createUserJob:
  defaultUser:
    enabled: true

logs:
  persistence:
    enabled: false
    # TODO: Enable later on
    # enabled: true
    # existingClaim: eve-airflow-logs-pvc

# POLISH later
# pgbouncer:
#   enabled: true
#   configSecretName: airflow-pgbouncer-config # TODO
#   metricsExporterSidecar:
#     statsSecretName: airflow-pgbouncer-stats # TODO

# POLISH later
# databaseCleanup:
#   enabled: true
#   retentionDays: 90
