version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s|%(name)s] %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  stderr:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard
    stream: ext://sys.stderr

loggers:
  ingest:
    level: INFO
    handlers:
      - stderr
    propagate: true

root:
  level: WARNING
  handlers:
    - stderr
